In [ ]:
import numpy as np

In [ ]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

In [ ]:
#Simple indexing
[x[3], x[7], x[2]]

In [ ]:
#Fancy indexing
ind = [3, 7, 4]
x[ind]

In [ ]:
X = np.arange(12).reshape((3, 4))
print(X)
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

In [ ]:
X[row[:, np.newaxis], col]

In [ ]:
row[:, np.newaxis] * col

In [30]:
print(X)
X[2, [2, 0, 1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([10,  8,  9])

In [31]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [32]:
mask = np.array([1, 0, 1, 0], dtype=bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])